### ISSUE TITLE
Is it possible to keep the number of rows unchanged?

### ISSUE THREAD

**Issue by khdhhde21** [uvarov-frontend/vanilla-calendar-pro#161]
Is it possible to keep the number of rows unchanged? For example, there are 6 rows in December 2023, but only 5 in January 2024. I understand that this happens because weeks don't perfectly align with months in the actual calendar, but it does create somewhat unpleasant changes of the calendar height. Is there a setting that can help alleviate this issue?

**Comment by uvarov-frontend** [comment]
Fix the height of the calendar via css

**Comment by khdhhde21** [comment]
But then the day cell dimensions will not be constant:

![jan](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/33406277/288583e4-06b3-41e7-b4aa-7696918cc18e)
![dec](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/33406277/cd184092-300a-4079-880a-a807975feaa4)

**Comment by uvarov-frontend** [comment]
That's right, the number of lines in the calendar will be different, there is no way to fix it.

**Comment by khdhhde21** [comment]
Thank you.
