### ISSUE TITLE
Selected month with enabledDates

### ISSUE THREAD

**Issue by delanfranchi** [uvarov-frontend/vanilla-calendar-pro#164]
Hi, first, thanks for this great work. really. 

I I'm currently working on a date selection web component for a ticketing service.
I've tried to initialise the calendar with only a few selectable days, as well as initialising the datepicker in the first month of the first date.

One date is enabled in december, and  two in january.
But when i select january, all days beetween the first day and the last date of january are enabled.

**Demo :**  (slow on codepen...)
https://codepen.io/delanfranchi/pen/YzBBLBe?editors=1111

``` 
const options = 
  {
   settings:{
     lang:"fr",
     range:{
       enabled:["2023-12-14","2024-01-08","2024-01-27"],
       disableAllDays:true,
     },
     selected:{
         month:11,
         year:2023
       }
     }
  }
;
                            
const calendar = new VanillaCalendar('.c-calendar', options);
calendar.init();
```

Thanks a lot.

**Comment by uvarov-frontend** [comment]
Hi. Thank you for reporting the problem, I will fix it in the next issue. In the meantime, as a temporary solution, you can use an earlier version 2.7.2 that does not contain this bug. https://cdn.jsdelivr.net/npm/@uvarov.frontend/vanilla-calendar@2.7.2/build/vanilla-calendar.min.js
