### ISSUE TITLE
Safari 12: height: 100%; accepts the entire height of the parent.

### ISSUE THREAD

**Issue by artemsites** [uvarov-frontend/vanilla-calendar-pro#179]
The layout of the calendar goes to safari.
height: 100%; accepts the entire height of the parent.

![image](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/24230199/1563d313-c54c-424f-bb5e-682c436df004)

**Comment by uvarov-frontend** [comment]
Thanks for reporting the issue, you can set `height: auto` for these elements, I will fix it in future versions.
