### ISSUE TITLE
Programmatically set/update range of pre-selected dates in input mode.

### ISSUE THREAD

**Issue by SohanChotia** [uvarov-frontend/vanilla-calendar-pro#180]
I need to set a pre-selected date range in input mode. But it doesn't seem to work.

I tried setting

` selected:
dates: ['2024-01-09:2024-02-13'],
 month: 1,
 year: 2024
`

as explained in here [https://vanilla-calendar.pro/docs/learn/date-management/selected-days-month-year-by-default](url)

Also doing `calendar.update()` also has an issue.

In input mode, actual calendar is not appended in DOM until user clicks on input element. So when we do

`calendar.update()`

It just messes up and inserts calendar html in place of input element.

Please suggest how can I make it work ?

**Comment by uvarov-frontend** [comment]
You can use [actions.showCalendar()](https://vanilla-calendar.pro/ru/docs/reference/additionally/actions#actions-show-calendar) and perform any action you need in it.

**Comment by uvarov-frontend** [comment]
Специально для вас: https://codesandbox.io/p/sandbox/vibrant-raman-5f6klz?file=%2Fcalendar.ts

```
import VanillaCalendar, { Options } from "vanilla-calendar-pro";
import "vanilla-calendar-pro/build/vanilla-calendar.min.css";

const options: Options = {
  input: true,
  settings: {
    selection: {
      day: "multiple",
    },
    selected: {
      dates: ["2022-01-09:2022-01-13", "2022-01-22"],
      month: 0,
      year: 2022,
    },
  },
  actions: {
    showCalendar(self) {
      self.settings.selected.dates = ["2024-01-09:2024-02-13"];
      self.update({ dates: true });
    },
  },
};

const calendarInput = new VanillaCalendar("#calendar-input", options);
calendarInput.init();
```

**Comment by SohanChotia** [comment]
How it will react with respect to disabled dates. e.g 

if I have dates disabled from 4-Jan to 10-Jan. and I set selected dates from 7-Jan to 15-Jan

**Comment by uvarov-frontend** [comment]
These will be included in `self.settings.selected.dates`. If you don't need it, you can write a function there that will create a new array of selected dates without the disabled dates, and then apply them to `self.settings.selected.dates`.

**Comment by uvarov-frontend** [comment]
#189
