### ISSUE TITLE
Question: How to add responsive CSS to multiple months?

### ISSUE THREAD

**Issue by robsontenorio** [uvarov-frontend/vanilla-calendar-pro#181]
I am trying to upgrade MaryUI calendar  to latest version as suggest by you. 

On `2.7.0` I have used a dirty hack to make multiple month responsive. But, I can't achieve the same on `2.9.2`.

Bellow is working with `2.7.0`:

https://mary-ui.com/docs/components/calendar#multiple-months

https://github.com/robsontenorio/mary/blob/main/src/View/Components/Calendar.php#L54

<img width="546" alt="image" src="https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/118955/37e3748d-e1e6-4573-8fbc-5e8e07dfef20">

**Comment by uvarov-frontend** [comment]
Hi, I applied your styles for responsiveness for 2.9.2 and I don’t see a problem, it works the same. May I know more about the problem?
Look: https://dsh.re/04568

**Comment by robsontenorio** [comment]
@uvarov-frontend Can I ask you what exactly elements did you placed the css classes ?

**Comment by uvarov-frontend** [comment]
I just took the ones you have here https://github.com/robsontenorio/mary/blob/main/src/View/Components/Calendar.php#L54

```
.vanilla-calendar_multiple {
  width: fit-content;
}

.vanilla-calendar-grid {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}
```
I use gap for spacing between calendar instances, but when used in conjunction with display: flex, gap has later browser support compared to 'display: grid'. Therefore, adaptability depends on the explicitly specified width of .vanilla-calendar_multiple.

**Comment by robsontenorio** [comment]
@uvarov-frontend 

What case do you think it should not be responsive?
Because otherwise we could make it responsive by default on Vanilla Calendar source code.

**Comment by robsontenorio** [comment]
@uvarov-frontend Thank you! Looking forward.
