### ISSUE TITLE
Firefox 52 main div height fills the window.

### ISSUE THREAD

**Issue by whataboutpereira** [uvarov-frontend/vanilla-calendar-pro#184]
In Firefox 52 the main calendar container is extended to the bottom of the page.

![image](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/22724651/662c43b8-ea21-4d04-8d17-0c2d23e9ff88)

This is caused by `bottom: 0` in `.vanilla-calendar_to-input` CSS class.

It's overriden by `height: max-content` in newer browsers, so the problem likely exists in all browsers that don't support max-content.

**Comment by uvarov-frontend** [comment]
Thanks for the message, the problem is known. #179
