### ISSUE TITLE
Date selection doesn't work with input: true.

### ISSUE THREAD

**Issue by whataboutpereira** [uvarov-frontend/vanilla-calendar-pro#189]
As can be seen here `selected: [...dates]` works in regular mode, but not in `input` mode:

https://codesandbox.io/p/sandbox/blissful-pike-gxy6wt

I can see from someones code in discussions that it has worked in v 2.7.0.

Also I think the selected date(s) should also be loaded into the input when the calendar is initialized with the option. Or it should maybe work the other way if there's already a date in the input value that should be loaded into the calendar.

If this all worked, it would be possibly to have a button to select today's date.

**Comment by whataboutpereira** [comment]
The more I think about it, reading the initial value from input should probably be the default behaviour. That way the calendar and input would be in sync.

**Comment by whataboutpereira** [comment]
At a glance the `self.input` condition should also call `setVariables(self)` here. That way the selected date is actually selected. But input field itself stays empty. One would need to deselect and then select it again to actually apply the value.

https://github.com/uvarov-frontend/vanilla-calendar-pro/blob/3a5b69c693982f770b1942beaaaabaeaa597c0a1/package/src/scripts/init.ts#L11-L18

**Comment by whataboutpereira** [comment]
With the added setVariables(self) I can do this after init to get the input and calendar in sync.

```
calendar.init();

if (calendar.selectedDates[0]) {
    calendar.HTMLInputElement.value = calendar.selectedDates[0];
}
```

I now understand that it's not possible to read date(s) from input value, because the value there is defined by the user in changeToInput().

**Comment by whataboutpereira** [comment]
The problem still remains - without setVariables() calendar.selectedDates will remain undefined after init().

Without input mode selectedDates will be correctly set to ['2024-01-26'] in init() when set via settings.selected.dates.

**Comment by uvarov-frontend** [comment]
Because when the calendar is initialized it is not yet created in the DOM if `input: true` is used.
The calendar is created after the first click on `input`. At this moment, all "Read-Only Parameters" are filled in. Up to this point they are uncertain.

**Comment by uvarov-frontend** [comment]
You can get `selectedDates` after the calendar has been created in the DOM using the `showCalendar()` method.
https://vanilla-calendar.pro/docs/reference/additionally/actions#actions-show-calendar

**Comment by uvarov-frontend** [comment]
The idea is to optimize the number of calendars with "enter" and not perform operations that may not be necessary if the user did not press "enter" while on the page.
The setVariables module is large enough to compute, so it is a calendar optimization measure.
You can make an option that will determine how setVariable will be executed immediately after initializing the calendar with `input` or “on demand”, but this is definitely not worth doing by default.

**Comment by whataboutpereira** [comment]
Thanks for the explanation. I've now worked around the previous way I worked around this. :)
