### ISSUE TITLE
Issue with modifier on popups

### ISSUE THREAD

**Issue by Drleugim** [uvarov-frontend/vanilla-calendar-pro#196]
I'm using the popups in the calendar, but the "modifier" key is not working.

I'm adding 
`popups: { '2022-06-28': { modifier: 'bg-red color-pink', }, }`
as seen on the documentation but the background color of the day is not changing.

I'm using react and creating the component just as the documentation shows

Thanks!

**Comment by uvarov-frontend** [comment]
You need to create a class in css and set the properties you need for it.
