### ISSUE TITLE
DissableAllDays issue

### ISSUE THREAD

**Issue by rmn-plk** [uvarov-frontend/vanilla-calendar-pro#206]
Если не передавать ничего в enabled, будет доступна первая дата текущего месяца.
Наверно все-таки будет логичнее, чтобы вообще не было доступных дат.

Демо:
https://codepen.io/rmn-plk/pen/jOJzxrN

**Comment by uvarov-frontend** [comment]
Спасибо за отчет, исправлю в след версии.
