### ISSUE TITLE
font-size & dimensions appears too small due to root font-size discrepancy!

### ISSUE THREAD

**Issue by kumardeepakxyz** [uvarov-frontend/vanilla-calendar-pro#207]
The plugin primarily uses rem units for styling, while my project's base font size is set to 10px. This difference in root font size causes the calendar elements to appear significantly smaller than intended. Calendar elements appear too small and visually unbalanced.

I'd greatly appreciate it if you could point me towards a more permanent solution for this issue, as overriding numerous values feels like a temporary fix and might break in future updates.

![plugin_issue](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/36254505/d34e2e26-f1ee-459c-9c60-640cf6a91de8)

**Comment by kumardeepakxyz** [comment]
Additionally, is there a method to display the calendar upon input focus?

It can be quite frustrating when the calendar fails to activate upon focusing on the input field from the previous entry. 🤨

Enabling this as a default behaviour would greatly enhance user experience, as currently it is only activated by click.

**Comment by uvarov-frontend** [comment]
@kumardeepakxyz Regarding the font size. The calendar uses tailwind for styling and it just so happens that they use `rem`. I haven't found a way to solve this problem for you other than assigning font sizes yourself or using `transform: scale()`.

I absolutely agree with the second remark (display the calendar upon input focus), it will be added in the next version. Thanks for the report.
