### ISSUE TITLE
The documentation page doesn't work

### ISSUE THREAD

**Issue by amavica** [uvarov-frontend/vanilla-calendar-pro#210]
The page https://vanilla-calendar.pro/docs/reference/main/main-settings doesn't load.
I tried in different browsers and devices.

**Comment by uvarov-frontend** [comment]
Fixed, thanks!

**Comment by ghiscoding** [comment]
@uvarov-frontend it doesn't work again, but it was working 2 weeks ago. Now it seems to be stuck to the main page, clicking on "Docs" or "Learn" does nothing, but I remember that it worked just a week or two ago, so it's a bit strange

**Comment by uvarov-frontend** [comment]
@ghiscoding I use next js v14.0.0 for the site, the site itself stops working after a month of operation. I'll look into it, thanks for letting me know.
