### ISSUE TITLE
Is there a method to display the calendar upon input focus?

### ISSUE THREAD

**Issue by uvarov-frontend** [uvarov-frontend/vanilla-calendar-pro#211]
Additionally, is there a method to display the calendar upon input focus?

It can be quite frustrating when the calendar fails to activate upon focusing on the input field from the previous entry. 🤨

Enabling this as a default behaviour would greatly enhance user experience, as currently it is only activated by click.

_Originally posted by @kumardeepakxyz in https://github.com/uvarov-frontend/vanilla-calendar-pro/issues/207#issuecomment-1949888007_

**Comment by kumardeepakxyz** [comment]
Hello @uvarov-frontend, there seems to be an issue with the `top` position of the calendar. It appears to be too distant from the input, more aligned with the top of the page. I've updated to the latest version, but the problem still persists.

**Comment by kumardeepakme** [comment]
Any update on this?

**Comment by ghiscoding** [comment]
@kumardeepakme you can contribute to the project, I didn't really test it (not sure how to test it either) but taking the code from 

https://github.com/uvarov-frontend/vanilla-calendar-pro/blob/501f311faf141414acfd7f9bf17ea52490a15dff/package/src/scripts/handles/handleInput.ts#L64-L73

and changing to this new code, might be enough. You should test it out and contribute a Pull Request if it works
```ts
const inputOpenPicker = () => {
	if (firstInit) {
		cleanup.push(createCalendarToInput());
	} else {
		setPositionCalendar(self.HTMLInputElement, self.HTMLElement, self.settings.visibility.positionToInput, self.CSSClasses);
		self.show();
	}
	window.addEventListener('resize', handleResize);
	document.addEventListener('click', documentClickEvent, { capture: true });
};

self.HTMLInputElement.addEventListener('click', inputOpenPicker);
self.HTMLInputElement.addEventListener('focus', inputOpenPicker); // reference same open picker fn for `focus` event

```
