### ISSUE TITLE
add better package Types exports

### ISSUE THREAD

**Issue by ghiscoding** [uvarov-frontend/vanilla-calendar-pro#224]
Hello, I'm starting to look at date picker alternative and your project seems quite interesting and nice. However, I just took a quick look if you provided any `exports` in your `package.json` and you don't and this could be a problem for proper CJS/ESM and Types (d.ts) detection. You can see the problem if you visit the [Are the types wrong?](https://arethetypeswrong.github.io/?p=vanilla-calendar-pro) website (which was created by a TypeScript maintainer), below is the result of your project returned from that website.

![image](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/643976/064b786a-2514-4f5a-8007-d0b1db20b0ed)

for my libraries, I typically use something along these (notice the `exports` that you are missing)

```json
{
  "main": "./dist/my-lib.cjs",
  "module": "./dist/my-lib.js",
  "types": "dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "node": "./dist/my-lib.cjs",
      "import": "./dist/my-lib.js",
      "require": "./dist/my-lib.cjs"
    },
    "./package.json": "./package.json"
  }
}
```
with this exports, the result from "Are the types wrong?" changes to all good. 

So this is just a suggestion since like I said I am not using your library yet but I might in the future... Cheers.

**Comment by uvarov-frontend** [comment]
Thank you, this is very interesting, I think adding the necessary exports will not be a big problem for me 😅. I'll do this in the next release.
