### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by uvarov-frontend** [uvarov-frontend/vanilla-calendar-pro#233]
### Discussed in https://github.com/uvarov-frontend/vanilla-calendar-pro/discussions/226

<div type='discussions-op-text'>

<sup>Originally posted by **batgithub** March  1, 2024</sup>
Hi,
This project is looking fantastic 🙂

But, I didn't find any information about accessibility, so I'm not sure if It's safe to use in this area.
When I check about accessibility calendar, they use table and aria stuff.

Is there anybody who have feedback on this topic ?</div>

**Comment by acollazo25** [comment]
[Awesome project](https://github.com/sorrycc/awesome-javascript), maybe some improvements in this topic would be:

- Include the `tabindex` attribute appropriately on the day elements and their parent container, to improve the group selection experience.
- Add the `aria-label` attribute in the day elements.
- Add the `aria-current` attribute on the selected day element with the `date` value.

Great job!

**Comment by uvarov-frontend** [comment]
Implemented in v3.0.0 #293
