### ISSUE TITLE
Display programatically selected date range in date picker

### ISSUE THREAD

**Issue by leevigraham** [uvarov-frontend/vanilla-calendar-pro#239]
Slightly related to https://github.com/uvarov-frontend/vanilla-calendar-pro/issues/180

I need to show a range of selected dates in the picker when a date input is updated:

eg if a user edits either of the date inputs I want the calendar to update.

From the previous ticket I can see that I can update the calendar with: 

```
this.calendar.settings.selected.dates = ["2024-04-15"];
this.calendar.update({ dates: true });
```

I'm also guessing there is some kind of internal function of calculating the range?

![image](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/25124/0a89ac38-7e4b-419c-b8af-021d2dfa8872)

**Comment by uvarov-frontend** [comment]
https://vanilla-calendar.pro/docs/reference/additionally/settings#selected-dates
this.calendar.settings.selected.dates = ["2024-03-14:2024-03-16"];
this.calendar.update({ dates: true });
