### ISSUE TITLE
Suggestion. Improvements for the custom class names.

### ISSUE THREAD

**Issue by o2sevruk** [uvarov-frontend/vanilla-calendar-pro#247]
I noticed a problem with custom classes. E.g. the plugin provides the ability to change classes using the `CSSClasses` parameter. But you can't add multiple classes. No, in some cases you can, but after that you will have problems. For example. I can change the `dayBtn` class like this:
```
CSSClasses: {
  dayBtn: 'class-1 class-2 class-3'
}
```
at first glance it works well, but when you select the date you will catch the error because the code is like this:
```
const arrowEl: HTMLElement | null = element.closest(`.${self.CSSClasses.arrow}`);
```
Instead of using classes, I suggest you use another attribute, e.g. `data-arrow` for functionality and keep the classes just for styling.

**Comment by uvarov-frontend** [comment]
That’s right, you can change one class to another, but not to several. It’s not provided for and shouldn’t work that way.

**Comment by jahaganiev** [comment]
Hey @uvarov-frontend - thanks for the reply!

At [Preline](https://preline.co/) we wanted to integrate your awesome datepicker plugin under third party libraries and would like to know if you have any roadmap to support TailwindCSS in future.

Cheers!
Jaha

**Comment by uvarov-frontend** [comment]
@jahaganiev Good afternoon.
I'll add this to my roadmap.

**Comment by jahaganiev** [comment]
Good Day @uvarov-frontend, 

Our team created PR [here](https://github.com/uvarov-frontend/vanilla-calendar-pro/pull/260) regarding the above suggestion. Please have a look when you have time and let us know if you need any help with that.

Cheers!
Jaha

**Comment by uvarov-frontend** [comment]
> Good Day @uvarov-frontend,
> 
> Our team created PR [here](https://github.com/uvarov-frontend/vanilla-calendar-pro/pull/260) regarding the above suggestion. Please have a look when you have time and let us know if you need any help with that.
> 
> Cheers! Jaha

Good afternoon, I see you have added partial support for multiple CSS classes, for which you are very grateful, but I plan to completely move away from CSS classes in my code, and transfer all dependencies to data attributes, I will add commits to your PR.

**Comment by jahaganiev** [comment]
> > Good Day @uvarov-frontend,
> > Our team created PR [here](https://github.com/uvarov-frontend/vanilla-calendar-pro/pull/260) regarding the above suggestion. Please have a look when you have time and let us know if you need any help with that.
> > Cheers! Jaha
> 
> Good afternoon, I see you have added partial support for multiple CSS classes, for which you are very grateful, but I plan to completely move away from CSS classes in my code, and transfer all dependencies to data attributes, I will add commits to your PR.

Good Day @uvarov-frontend! Awesome, we look forward forward for that and please feel free to let us know if you need any help. Thanks!

**Comment by uvarov-frontend** [comment]
Implemented in v3.0.0 #293

**Comment by jahaganiev** [comment]
Thanks again for the work @uvarov-frontend - we've fully integrated into Preline UI components https://preline.co/docs/advanced-datepicker.html

**Comment by uvarov-frontend** [comment]
> Thanks again for the work @uvarov-frontend - we've fully integrated into Preline UI components https://preline.co/docs/advanced-datepicker.html

Yes, I've already seen traffic from your site to my site today, 😄 your library looks really cool, I'm really glad that my calendar was useful to you, it's really cool!

**Comment by jahaganiev** [comment]
Awesome! Thanks - supper happy that we came across with your library, it's really well featured and written! ❤️
