### ISSUE TITLE
Invalid bem class

### ISSUE THREAD

**Issue by rmn-plk** [uvarov-frontend/vanilla-calendar-pro#248]
В этом примере:
https://vanilla-calendar.pro/ru/docs/learn/customization-and-modification/css-classes

Когда переопределяем класс стрелочки остаются классы:
vanilla-calendar-arrow_prev vanilla-calendar-arrow_next,

без родительского класса:
vanilla-calendar-arrow

**Comment by uvarov-frontend** [comment]
Спасибо за отчет.
Это сделано намеренно и не является ошибкой. Вы можете назначить любое другое имя класса.
