### ISSUE TITLE
Allow to position the calendar relative to an element.

### ISSUE THREAD

**Issue by whataboutpereira** [uvarov-frontend/vanilla-calendar-pro#259]
Right now the calendar attaches itself to the end of body in input mode.

It would be nice to be able to attach it relative to a given element as this would alleviate some z-index issues when the calendar is for example used inside a modal that covers the view. Also with relative positioning repositioning on scroll and resize wouldn't always be needed.

I tried moving the calendar after the input element in initCalendar(), but it is still positioned relative to the page.

**Comment by uvarov-frontend** [comment]
I'll think about what can be done, thanks for the report!

**Comment by uvarov-frontend** [comment]
Related to #235
