### ISSUE TITLE
bug with disableGaps when only one disabled date

### ISSUE THREAD

**Issue by ligne13** [uvarov-frontend/vanilla-calendar-pro#262]
Hi,

it seems disableGaps does not work if there is only one disabled date in the range.

In this example: https://codesandbox.io/p/sandbox/pedantic-easley-6xjsqf?file=%2Fcalendar.ts%3A16%2C7, May 23rd is disabled, but it is possible to select a range starting on May 22nd and finishing on May 24th.

However if you change the disabled setting to a range of dates (example: disabled: ["2024-05-23:2024-05-24"]) the disableGaps setting is working.

Is this a bug with the disableGaps setting?

Thank you

**Comment by uvarov-frontend** [comment]
Thanks for the report, I wanted to look into the problem, but such a sandbox does not exist, 404 error, could you reproduce the problem again?

**Comment by jigsaw1270** [comment]
hi @uvarov-frontend , I ran into  the same  issue . I tried  to  reproduce  it - https://codesandbox.io/p/sandbox/divine-sun-6lzp6h?file=%2Fcalendar.ts   as  u can see i have  disabled 28th august in the ranged  calendar and but  when i try  to  select  the dates it is  letting  me  select  it, while  if  i disable  two dates it  works  perfectly fine . Would highly  appreciate if u can look into  the  issue and provide a solution for  this  error/bug.

**Comment by uvarov-frontend** [comment]
Thanks, fixed. [0d9e1db](https://github.com/uvarov-frontend/vanilla-calendar-pro/commit/0d9e1db33a7abfc60ba243c1e73ef7a317800e72)
