### ISSUE TITLE
Button outline obscured by adjacent button.

### ISSUE THREAD

**Issue by whataboutpereira** [uvarov-frontend/vanilla-calendar-pro#263]
![image](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/22724651/cb241762-d7ba-4a1f-8141-059907a86dfa)

This can be fixed by adding:

```
.vanilla-calendar button:focus-visible {
    outline-offset: -1px;
}
```

**Comment by uvarov-frontend** [comment]
Thank you my friend, I will definitely add this in the updated version.
