### ISSUE TITLE
No arrows when using `month` type

### ISSUE THREAD

**Issue by wongcheehong** [uvarov-frontend/vanilla-calendar-pro#264]
I want to switch to next and previous year by using arrow only in `month` calendar . But there is no arrow button for me to switch

![image](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/11075969/102cd1df-246c-4406-bf75-ecf1ad62d47e)

Here is my options:
```
{
  type: 'month',
  settings: {
    selection: {
      year: 'only-arrows'
    }
}
```

**Comment by uvarov-frontend** [comment]
This is not how it should work, the arrows switch months, not the year, and since you have the “months” display mode selected, the year can only be changed by clicking on the corresponding heading.

**Comment by wongcheehong** [comment]
As I want the the button to behave like so, and the package not allow me to do so, I insert the arrow button dynamically using DOM manipulation.
