### ISSUE TITLE
Disable year and month but keep nav arrows

### ISSUE THREAD

**Issue by saidcc** [uvarov-frontend/vanilla-calendar-pro#265]
Hello,

There is actually two questions

1. Is it possible for the arrow navigation to remain active while the month and year are disabled? I'm uncertain if it's a bug, but after a few clicks, either the month or the year becomes disabled, rendering further navigation impossible. See image below
![image](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/67986950/9a486ccd-9040-4875-b87b-e899efa24c18)

2. Is it possible to disable the appy/insert button if there is no selection made, in that there is no start or end date

Thanks & Regards
Said

**Comment by uvarov-frontend** [comment]
Hello, I don't see the problem from the picture, reproduce the problem on https://codesandbox.io and attach the link here.
