### ISSUE TITLE
Set default month and year to null

### ISSUE THREAD

**Issue by wongcheehong** [uvarov-frontend/vanilla-calendar-pro#266]
When using the `month` and `year` types, the calendar selects the current month and year by default. Is it possible to set it to `null`? I know we can override the default. But I want the user to select their initial value instead of having the current month or year pre-selected.

**Comment by uvarov-frontend** [comment]
How do you imagine that? What initial interface should the calendar have if no month and year are selected? No, It is Immpossible.

**Comment by wongcheehong** [comment]
For month view, you can set year to current year, but don't set the month to current month, let user choose.
For year view, you can initially show current year, but don't make the current year as selected

**Comment by uvarov-frontend** [comment]
Sorry, but the logic behind this calendar is that the displayed month/year = the selected month/year.
