### ISSUE TITLE
Multiple selected date ranges

### ISSUE THREAD

**Issue by mlundela** [uvarov-frontend/vanilla-calendar-pro#268]
If more than one date range is specified for _selected.dates_, then they are displayed as one range. The overlapping day should be possible to style differently.

<img width="268" alt="Screenshot 2024-06-23 at 12 20 25" src="https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/16946/6d116362-c5d1-40f8-980f-8298b7652bc5">

```
const calendar = new VanillaCalendar('#read-only-calendar', {
  type: 'multiple',
  settings: {
    selection: {
      day: 'multiple-ranged',
    },
    selected: {
      dates: [
        '2024-06-01:2024-06-08',
        '2024-06-08:2024-06-15',
      ],
    },
    range: {
      disableAllDays: true,
    },
  }
});
```

If ranges do not overlap, then intermediate start and end dates are not styled correctly:
<img width="267" alt="Screenshot 2024-06-23 at 12 20 08" src="https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/16946/fdf3f343-dc0e-4fc2-a959-e9cc6c70844e">

```
const calendar = new VanillaCalendar('#read-only-calendar', {
  type: 'multiple',
  settings: {
    selection: {
      day: 'multiple-ranged',
    },
    selected: {
      dates: [
        '2024-06-01:2024-06-06',
        '2024-06-08:2024-06-14',
      ],
    },
    range: {
      disableAllDays: true,
    },
  }
});
```

My style override:
```
#read-only-calendar .vanilla-calendar-day__btn_selected {
  background-color: #f2295b;
}
```

**Comment by uvarov-frontend** [comment]
This is the expected behavior by default, it was intended, you can style the calendar to suit your needs, as you think is right. CSS modifier classes are enough for this.
