### ISSUE TITLE
Using calendar with input and calling `.update()` method before opening calendar picker reassigns overrides the input

### ISSUE THREAD

**Issue by uvarov-frontend** [uvarov-frontend/vanilla-calendar-pro#274]
### Discussed in https://github.com/uvarov-frontend/vanilla-calendar-pro/discussions/267

<div type='discussions-op-text'>

<sup>Originally posted by **ghiscoding** June 21, 2024</sup>
It looks like if we set selected dates and then call `.update({ ... })` **before** the calendar picker had time to be created (before opening the picker), it will override (reassign) the input to be the calendar picker element. This is unexpected, it not breaks the styling but also cause leakage because instead of having a single picker element, after opening the picker via the input, it now has 2 inputs instead of 1 causing the leaking. 

Here's the updated code sandbox with the code to test with
https://codesandbox.io/s/cold-hill-94mq9f?file=/calendar.ts

If we call `.update()` , we can see below that the input is reassigned to be the calendar picker element

![image](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/643976/73785bbe-bfae-4cea-a5c7-34a25ff8da7c)

![brave_Yjlsbl4Vfw](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/643976/c8cf29ff-aca6-4735-a36e-3b41b65fc5aa)

but if we first click on the input and open the calendar picker, then the input remains untouched and works as intended

![brave_gsJGDWyFhT](https://github.com/uvarov-frontend/vanilla-calendar-pro/assets/643976/8ea85205-28ac-48b2-8cb6-068905704944)

You can reproduce via the codesandbox above and/or use this piece of to execute `.update()` on a button click before opening the calendar picker

```ts
document.querySelector("#select-date").addEventListener("click", () => {
  calendarInput.settings.selected = {
    dates: ["2023-04-07"],
    month: 3,
    year: 2023
  };
  calendarInput.update({
    dates: true,
    month: true,
    year: true,
    time: true
  });
  calendarInput.HTMLInputElement!.value = "2023-04-07";
});
```

The only way I can think of fixing this issue is somehow do an explicit init of the picker (creating the picker before calling the update but keep it hidden) so that when we call the update, it finds the correct picker.</div>

**Comment by ghiscoding** [comment]
hello, I have a fix in my project fork. I can apply the fix after all my new PRs are reviewed. :)
