### ISSUE TITLE
programmatic prev and next month?

### ISSUE THREAD

**Issue by wishdevs** [uvarov-frontend/vanilla-calendar-pro#288]
Is there a way to call the go previous month go next month function on an instance?

ex)
const calendar = new VanillaCalendar('#calendar', options);
calendar.init();

calendar.changeMonth(date: Date)
or
calendar.nextMonth()

**Comment by uvarov-frontend** [comment]
Set the month in options after initialization and update the calendar. (https://vanilla-calendar.pro/docs/reference/additionally/settings#selected-month)
For example:
```
const calendar = new VanillaCalendar('#calendar');
calendar.init();
calendar.settings.selected.month = 5;
calendar.update({ month: true });
```
