### ISSUE TITLE
themeDetect is not working as expected

### ISSUE THREAD

**Issue by u5r0** [uvarov-frontend/vanilla-calendar-pro#290]
> [Docs](https://vanilla-calendar.pro/docs/reference/additionally/settings#visibility-themeDetect)

Hello, thank you for the good work

Just a quick question, if I toggle between theme manually, which goes for `light`:
```html
<html lang="ar" data-theme="light">
````
and for `dark`:
```html
<html lang="ar" data-theme="dark">
```
Isn't `themeDetect` supposed to just toggle the calendar theme just by detecting the `data-theme` attribute?

**Comment by uvarov-frontend** [comment]
Hi, that’s right. If that’s not the case, create a problem in any sandbox, I’ll see.

**Comment by u5r0** [comment]
It works in a sandbox. 
It doesn't work (I mean detecting data-theme html attribute) in my code unless I switch calendar headers (year or month).
It's an html / css native setup. Anyhow thanks for your quick reply!
