### ISSUE TITLE
One day shift down from the end date in type 'Multiple' calendar

### ISSUE THREAD

**Issue by RamezYoussef712** [uvarov-frontend/vanilla-calendar-pro#298]
first, I faced this unexpected behavior locally, whenever I select 2 days in 'multiple-ranged' that has 96 days or more difference, the end date is shifted one day less.
Then I tried to debug my initializing code as I suspected my code caused the bug, then I thought I should try reproducing the behavior using the documentation "Date Selection in Input". 
So I opened the multiple sandbox example: "https://codesandbox.io/p/sandbox/solitary-lake-kz4sjj?file=%2Fcalendar.ts&utm_medium=sandpack" ... And I found the same behavior but with higher days difference of 255 days ... I used exactly these dates to test in the sandbox "2024-08-19 — 2025-03-31"

**Comment by uvarov-frontend** [comment]
Demonstrate the problem in the recording and provide your time zone. In my time zone `GMT +3` I do not experience such a problem.
