### ISSUE TITLE
Update selected days at runtime

### ISSUE THREAD

**Issue by Kedaqusa1604** [uvarov-frontend/vanilla-calendar-pro#299]
Hi, first of all, thanks for sharing this project, it's awesome.
Second, is there any method that updates the selected dates at runtime after the calendar has been mounted?

for example:

```js
// options are not important for this example
const calendar = new VanillaCalendar("#calendar", {...options});
calendar.init();

// This is I would like to do:
calendar.setSelectedDates([date1, ...dateN]);
```` 

and then get the updated result in the calendar element in the DOM.

Thanks in advance for any help.

**Comment by ghiscoding** [comment]
You probably want the [`jumpToSelectedDate`](https://vanilla-calendar.pro/docs/reference/main/main-settings#jump-to-selected-date) option that I contributed recently, it will open the calendar at the first selected date. Behind the scene it does

```ts
const date1 = '2020-01-01';
calendarInstance.settings.selected = {
  dates: [date1, ...],
  month: 2, 
  year: 2020
}
```

**Comment by uvarov-frontend** [comment]
The method will be added in v3.0.0 - #293 (4th point), but for now you can change the selected dates as suggested above or like this:
```
calendar.settings.selected.dates = ['2024-08-29'];
calendar.update({ dates: true });
```

**Comment by johanrd** [comment]
@uvarov-frontend Is there a convenience method to update all options before/upon calling .update()? 

Now I specify all options I need to update separately:

```
this.vanillaCalendarInstance.popups = popups
this.vanillaCalendarInstance.selectedWeekends = options.selectedWeekends
this.vanillaCalendarInstance.selectedYear = options.selectedYear
this.vanillaCalendarInstance.selectedMonth = options.selectedMonth
this.vanillaCalendarInstance.selectedDates = options.selectedDates
this.vanillaCalendarInstance.selectedHolidays = options.selectedHolidays

this.vanillaCalendarInstance.update({
  dates: true,
  year: true,
  month: true,
});
```

Which is ok, I guess, but it could also have been like 

```
this.vanillaCalendarInstance.options = options
```
…or
```
this.vanillaCalendarInstance.update({
  dates: true,
  year: true,
  month: true,
}, newOptions)
```

**Comment by uvarov-frontend** [comment]
> @uvarov-frontend Is there a convenience method to update all options before/upon calling .update()? 
> 
> 
> 
> Now I specify all options I need to update separately:
> 
> 
> 
> ```
> 
> this.vanillaCalendarInstance.popups = popups
> 
> this.vanillaCalendarInstance.selectedWeekends = options.selectedWeekends
> 
> this.vanillaCalendarInstance.selectedYear = options.selectedYear
> 
> this.vanillaCalendarInstance.selectedMonth = options.selectedMonth
> 
> this.vanillaCalendarInstance.selectedDates = options.selectedDates
> 
> this.vanillaCalendarInstance.selectedHolidays = options.selectedHolidays
> 
> 
> 
> this.vanillaCalendarInstance.update({
> 
>   dates: true,
> 
>   year: true,
> 
>   month: true,
> 
> });
> 
> ```
> 
> 
> 
> Which is ok, I guess, but it could also have been like 
> 
> 
> 
> ```
> 
> this.vanillaCalendarInstance.options = options
> 
> ```
> 
> …or
> 
> ```
> 
> this.vanillaCalendarInstance.update({
> 
>   dates: true,
> 
>   year: true,
> 
>   month: true,
> 
> }, newOptions)
> 
> ```

There is a new method .set()
Try it calendar.set(newOptions, resetOptions)

**Comment by johanrd** [comment]
@uvarov-frontend wonderful, thanks!

**Comment by uvarov-frontend** [comment]
> @uvarov-frontend wonderful, thanks!

This method can be used before initialization as an alternative to the second parameter when creating an instance.
