### ISSUE TITLE
Select a range of the same day

### ISSUE THREAD

**Issue by melishev** [uvarov-frontend/vanilla-calendar-pro#304]
Hi, awesome library, you're beautiful.
My team and I had a question that we couldn't find the answer to in the documentation. Is there any way to set the date picker range to the same day? That is, when double-clicking on the same day, we would get ['2024-03-16', '2024-03-16'] on the output

**Comment by uvarov-frontend** [comment]
Hi, `selectedDates` can only contain unique selected dates, but you can get what you want using handlers, for example in your case you can use `clickDay`:
```
actions: {
    clickDay(event, self) {
      const dateStr = event.target.dataset.calendarDay;
      if (self.selectedDates.includes(dateStr)) return;
      self.selectedDates.push(dateStr, dateStr);
      console.log(self.selectedDates);
    },
  }
```
Sandbox example: https://codesandbox.io/p/sandbox/suspicious-sound-y7fmm2?file=%2Fcalendar.ts
Also look: https://vanilla-calendar.pro/docs/reference/main/main-settings#toggle-selected
