### ISSUE TITLE
clickDay() does not provide the correct clicked date if selected dates are set in settings

### ISSUE THREAD

**Issue by b2z** [uvarov-frontend/vanilla-calendar-pro#305]
Hi, thank you for the great calendar.

I have an issue with `clickDay()` action. If I have an array of selected days set in calendar settings then `clickDay()` does not provide the correct clicked date if this date is in array of selected days.

For example, I have such array of selected days:
`['2024-09-02', '2024-09-15', '2024-09-24']`

When in calendar I click on '2024-09-02' then in `self.selectedDates` I have `['2024-09-15', '2024-09-24']`. Or if I click on '2024-09-15' then in `self.selectedDates` I have `['2024-09-02', '2024-09-24']`. 

So I cannot access the correct clicked date.

But when I click on the date that is not in selected date array then everything is correct.  For example if I click on '2024-09-17' then `self.selectedDates` has `['2024-09-17']`.

**Comment by uvarov-frontend** [comment]
Hi.
1. If you set several selected dates in the settings, then you need to configure `settings.selection.day = 'multiple'`;
2. When clicking on a date that is in `self.selectedDates`, by default, the date is removed from `self.selectedDates`, you need to either use [`toggleSelected: false`](https://vanilla-calendar.pro/docs/ reference/main/main-settings#toggle-selected) or get the date that was clicked in `clickDay()` as follows: `event.target.dataset.calendarDay`;
Here's an example:
https://codesandbox.io/p/sandbox/eager-shockley-t7p4xt?file=%2Fcalendar.ts 

If something does not correspond to the logic I stated, let me know.

**Comment by b2z** [comment]
@uvarov-frontend thank you very much for the fast response. 
`event.target.dataset.calendarDay` solved my problem 👍
