### ISSUE TITLE
Is it possible to hide or disable the weekend cells?

### ISSUE THREAD

**Issue by andrewdenham** [uvarov-frontend/vanilla-calendar-pro#307]
Hi,

I'm trying to see if it is possible to hide the weekend cells, so rows of 5 day week (Mon-Fri)?

I found something about [visibility.settings.weekend](https://vanilla-calendar.pro/docs/reference/additionally/settings#visibility-weekend), but this suggests that it only enables or disables the highlighting of those days? Which unless I'm misunderstanding isn't working in the [example](https://vanilla-calendar.pro/docs/learn/date-management/do-not-highlight-the-weekend-today)?
I can still hover and select the weekend days?

Thanks

**Comment by uvarov-frontend** [comment]
The `visibility.settings.weekend` removes the CSS class from weekends. And that's all.
Whatever you want can be done through CSS. Add a `display: none` property for each 6th and 7th class `vanilla-calendar-day`.
