### ISSUE TITLE
biletiki.store `This site can’t be reached`

### ISSUE THREAD

**Issue by johanrd** [uvarov-frontend/vanilla-calendar-pro#310]
[biletiki.store](https://biletiki.store/): 

<img width="920" alt="Screenshot 2024-10-22 at 09 27 52" src="https://github.com/user-attachments/assets/419fa049-8640-4f90-96b1-f30c790a5f65">

**Comment by uvarov-frontend** [comment]
My domain registration has expired, I need $50 to renew it. I don't see the point in spending my money on this. Later I will change the url in the documentation to the vanilla-calendar.pro subdomain

**Comment by johanrd** [comment]
I understand – sounds like a good plan:)

Feel free to close. Or keep as open until the link is replaced in the **Usage example` ** here https://vanilla-calendar.pro/docs/learn/getting-started/installation

**Comment by uvarov-frontend** [comment]
New address: [biletiki.vanilla-calendar.pro](https://biletiki.vanilla-calendar.pro/)
Corrected on the website.
