### ISSUE TITLE
Feature request: Allow ranges for popups

### ISSUE THREAD

**Issue by johanrd** [uvarov-frontend/vanilla-calendar-pro#312]
Problem: For ranges spanning multiple months, it would be powerful to be able to display a popover that specifies the start and end date of the range (so that you don't need to click-to-browse toward the start and end):

<img width="289" alt="Screenshot 2024-10-22 at 12 55 06" src="https://github.com/user-attachments/assets/ee399344-0933-402a-8f0b-5d2ca81c9ada">

**Possible solution 1: allow ranges in  popup keys?**
Allow to specify a range in the key of popups, e.g:
```js
popups: {
  '2024-01-18:2024-03-21': {
    modifier: 'bg-red',
    html: 'Start: 2024-01-18, End: 2024-03-21,
  },
},
```
 
 **Possible solution 2: add range settings for rangePopover?**
Allow to specify a range in the key of popups, e.g:
```js
settings: {
  range: {
    rangePopover: true,
  },
}
```

It is of of course possible to work around this by adding the same popover for each day

**Comment by uvarov-frontend** [comment]
That's interesting, I'll think about it, thanks for the idea

**Comment by ghiscoding** [comment]
That is indeed interesting, I guess option 1 is probably more locale (language) friendly since the user decides on the text to display. So a locale friendly approach would be better in my opinion

**Comment by uvarov-frontend** [comment]
Let's add this to v3.0.0 😉

```
// onCreateDateRangeTooltip: (self: VanillaCalendarPro, dateEl: HTMLElement, tooltipEl: HTMLElement, dateElBCR: DOMRect, mainElBCR: DOMRect) => string | undefined
onCreateDateRangeTooltip(self) {
  const createRow = (title: string, value: string) =>
    `<div style="text-align: left; white-space: nowrap">
      <span>${title}</span>
      <b>${value}</b>
    </div>`;

  return `
    ${createRow('Start:', self.private.selectedDates[0])}
    ${self.private.selectedDates[1] ? createRow('End:', self.private.selectedDates[1]) : ''}
  `;
}
```

https://github.com/user-attachments/assets/0db9c0b4-50ec-44e6-b458-5e3f1d5c6870

**Comment by johanrd** [comment]
wow, nice! :partying_face:
