### ISSUE TITLE
Dynamically Updating Disabled Dates

### ISSUE THREAD

**Issue by ioannis-psomadelis** [uvarov-frontend/vanilla-calendar-pro#315]
On the initial load(calendar init), when I pass unavailableDates into the range options, the calendar works perfectly. 
However, when navigating between months (using the navigation arrows), I try to update the disabled dates dynamically, but I'm not seeing any changes reflected in the DOM/calendar.

`the first init
const options = {
        range: {
          disabled: this.unavailableDates,
        },
      },
...
`

after patching 
`self.actions.updateUnavailableDates(self, newPrices); //custom function to pass the dates into the unavailableDates
self.update({dates: false,});
`

The new data is successfully added to the settings object, but it doesn't seem to reflect in the calendar.

**Comment by uvarov-frontend** [comment]
Hi, thanks for reporting the issue, I'll take a look and let you know.

**Comment by uvarov-frontend** [comment]
You can get a faster answer if you recreate the problem in any js sandbox. For example here: https://codesandbox.io

**Comment by ioannis-psomadelis** [comment]
Did some digging around, and refactored a lot of my code. 
It seems that I was updating twice the calendar after patching the new data, so the case was after updating twice the disabled dates were lost.
Case closed :)
