### ISSUE TITLE
Bug in clickMonth action

### ISSUE THREAD

**Issue by abdousami02** [uvarov-frontend/vanilla-calendar-pro#317]
![Screenshot from 2024-11-02 13-07-31](https://github.com/user-attachments/assets/d977db19-6035-4d70-b7e6-ce409b1b147a)
when add function `clickMonth()` in 'actions' options, the `self.selectedMonth` value is not the real month number.
Jan Month is -> 0
Dec Month is-> 11

**Comment by uvarov-frontend** [comment]
Please read the information above the sandbox.

`It's important to note that months are numbered starting from zero, where January corresponds to the zeroth month, and December is the eleventh.`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth
