### ISSUE TITLE
v3 regression, unexpected rounding on week start end if long range

### ISSUE THREAD

**Issue by johanrd** [uvarov-frontend/vanilla-calendar-pro#320]
`selectedDates: ['2024-11-06:2024-11-17']`

| Actual in v3  |      Expected (as in v2)    |
|----------|:-------------:|
|  <img width="258" alt="Screenshot 2024-11-03 at 13 02 03" src="https://github.com/user-attachments/assets/ff21b400-10b0-43eb-be92-c3526cdffedf">| <img width="250" alt="Screenshot 2024-11-03 at 12 59 48" src="https://github.com/user-attachments/assets/115d178f-d3c7-4dfb-b94f-8c26ab51248e"> |

when a range spans multiple weeks, i'd expect the middle of ranges not to be rounded (as in v2): It is helpful that it communicates that the range spans further, i.e. not to be confused with multiple ranges.

**Comment by uvarov-frontend** [comment]
By default, the calendar does not have multiple ranges, the rounding is intentional, but you can design your calendar at your own discretion.

**Comment by johanrd** [comment]
yes, I'd still argue that it is misleading to have rounded edges at weekstart and week end when a single range spans multiple weeks. It may confuse users – they do not know the inner workings of vanillla calendar. I am talking from a UX perspective here.

**None of the other calendars out there have this rounding behavior:**
## Vanilla calendar pro 2: https://vanilla-calendar.pro/
<img width="250" alt="Screenshot 2024-11-03 at 12 59 48" src="https://github.com/user-attachments/assets/cc1edfc1-11c5-4531-abf4-de24fde7610d">

## LitePicker:
<img width="285" alt="Screenshot 2024-11-03 at 13 22 05" src="https://github.com/user-attachments/assets/b59958eb-596a-4d56-a158-8146f335ebe2">

## EasePick:
<img width="314" alt="Screenshot 2024-11-03 at 13 23 27" src="https://github.com/user-attachments/assets/daa326fd-8e35-45cd-b702-2b0da7d57284">

## LightPick:
![gallery-5fba68ba1f838](https://github.com/user-attachments/assets/f46e4f73-51fb-4879-acbc-ab162e69ec2b)

## Date range picker: (https://www.daterangepicker.com/)
![gallery-5fba6b56bb0d5](https://github.com/user-attachments/assets/47f37d3e-56b4-407b-83f3-349bee8f3d52)



Therefore I consider this a bug to have this rounding behavior as default

**Comment by uvarov-frontend** [comment]
Вы правы, это логично, сделаю как вы предлагаете, но потребуется чуть больше изменений в стилях чем ваш коммит, так как есть опция `displayDatesOutside`.
