### ISSUE TITLE
Regression in v3? `disableAllDays: true` has no effect?

### ISSUE THREAD

**Issue by johanrd** [uvarov-frontend/vanilla-calendar-pro#326]
### v3: Create a calendar `settings.disableAllDays: true`
```js
new Calendar(element, {
      type: 'default',
      disableAllDays: true,
    }
}
```
See that all dates are still selectable

### v2: Create a calendar wit v2 `settings.range.disableAllDays: true`
```js
new Calendar(element, {
      type: 'default',
      range: {
         disableAllDays: true
      }
   }
}
```

See that no dates are selectable (as expected).

Or am I missing something? thanks

**Comment by uvarov-frontend** [comment]
See #316 
`disableAllDates: false, // settings.range.disableAllDays`

**Comment by johanrd** [comment]
oh, thanks, disableAllDates and not disableAllDays!

**Comment by johanrd** [comment]
congrats on the v3 public release, btw! thanks a lot:)
