### ISSUE TITLE
Feature request: Minimum - maximum range

### ISSUE THREAD

**Issue by afonic** [uvarov-frontend/vanilla-calendar-pro#331]
Use case: In some scenarios, like a hotel reservation engine, often there is a minimum or maximum amount of days that are allowed. It would be helpful if the calendar would enforce them during selection.

Possible solution: Two new config keys, for example `minSelectableRange` and `maxSelectableRange` that would take values in days. Then after the user selects the first date of the range only dates that would be more than the minimum and less than the maximum would be allowed to be clicked.

**Comment by afonic** [comment]
Fair enough! Are you kind enough to provide me with an example?

**Comment by uvarov-frontend** [comment]
Of course I can do this once as an exception:
```ts
  onClickDate(self, event) {
    const dateBtnEl = event.target as HTMLButtonElement;
    // no more and no less than 4 days
    const clampedValue = 4;
    if (self.context.selectedDates.length === 1) {
      const dateStr = (dateBtnEl.parentElement as HTMLElement).dataset.vcDate;
      const date = getDate(dateStr as FormatDateString);
      const minDate = new Date(date);
      const maxDate = new Date(date);
      minDate.setDate(minDate.getDate() - clampedValue);
      maxDate.setDate(maxDate.getDate() + clampedValue);
      const minDateStr = getDateString(minDate);
      const maxDateStr = getDateString(maxDate);

      self.set(
        { disableAllDates: true, enableDates: [`${minDateStr}:${maxDateStr}`] },
        { dates: false, month: false, year: false, locale: true }
      );
    }

    if (!self.context.selectedDates[1]) return;
    self.set({ disableAllDates: false, enableDates: [] }, { dates: false });
  }
```

https://codesandbox.io/p/sandbox/pensive-banzai-pgxwqh?file=%2Fcalendar.ts

**Comment by afonic** [comment]
Thanks a lot! I wasn't aware that I can use `self.set` to change the calendar settings on the fly, this will be very helpful.

Is there a way to sponsor this project?

**Comment by uvarov-frontend** [comment]
I'm just working on the new documentation for version 3, the `set` method has been added to it. There will be up-to-date documentation later.

For now, you can only support the development on Buy Me a Coffee: https://buymeacoffee.com/uvarov
I hope that later there will be a way to go directly through Github.

**Comment by afonic** [comment]
That's great, I've sent some your way.
