### ISSUE TITLE
Version of Vanilla Javascript Documentation

### ISSUE THREAD

**Issue by billpebert** [uvarov-frontend/vanilla-calendar-pro#332]
Hi, is there any docs version of VanillaJS beside the Typescript?
![image](https://github.com/user-attachments/assets/38420169-5c6e-49bc-bfcb-6da5ac65a197)

**Comment by ghiscoding** [comment]
see PR #328 and for migration details take a look at #316

**Comment by uvarov-frontend** [comment]
@ghiscoding He is not interested in the documentation for the new version, but in examples of implementation without TypeScript, only pure JavaScript.

**Comment by uvarov-frontend** [comment]
@billpebert You can use all the code from TypeScript files in your JS file, as it is the same programming language. Except for typing wrappers, which can be simply deleted.

I don’t plan to implement examples on pure JS without typing, as it has no practical use.
