### ISSUE TITLE
Website example doesn't work

### ISSUE THREAD

**Issue by Allmedialab** [uvarov-frontend/vanilla-calendar-pro#334]
Hi,

Great plugin! This example on your website doesn't work and I have problems with getting the time addition working. (second example).

```html
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/styles/index.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/index.js" defer></script>
  </head>
  <body>
    <div id="calendar"></div>
    <script>
      // Destructure the Calendar constructor
      const { Calendar } = window.VanillaCalendarPro;
 
      document.addEventListener('DOMContentLoaded', () => {
        // Create a calendar instance and initialize it.
        const calendar = new Calendar('#calendar');
        calendar.init();
      });
    </script>
  </body>
</html>
```

```ts
import { Calendar, type Options } from 'vanilla-calendar-pro';

import 'vanilla-calendar-pro/styles/index.css';

const options: Options = {
  selectionTimeMode: 24,
};

const calendar = new Calendar('#calendar', options);
calendar.init();
```

Can you please show a example that works including 24 hours time? If I get it working I will donate!

Thanks,

David

**Comment by uvarov-frontend** [comment]
Please create a problem as in the template. Be sure to attach an example of the problem in the online sandbox.

**Comment by Allmedialab** [comment]
https://vanilla-calendar.pro/docs/learn/installation-and-usage

The code underneath this text doesn't work
Local or CDN
If you need to quickly integrate Vanilla Calendar Pro without using build tools or package managers, you can include it via CDN or [download the archive](https://cdn.jsdelivr.net/npm/vanilla-calendar-pro@latest/package.zip) with the latest version and include it locally.

`<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/styles/index.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/index.js" defer></script>
  </head>
  <body>
    <div id="calendar"></div>
    <script>
      // Destructure the Calendar constructor
      const { Calendar } = window.VanillaCalendarPro;
 
      document.addEventListener('DOMContentLoaded', () => {
        // Create a calendar instance and initialize it.
        const calendar = new Calendar('#calendar');
        calendar.init();
      });
    </script>
  </body>
</html>`

**Comment by uvarov-frontend** [comment]
I'll fix it on the site tomorrow, use it now:
```html
<html>
  <head>
    <link
      href="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/styles/index.css"
      rel="stylesheet"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/index.js"
      defer
    ></script>
  </head>
  <body>
    <div id="calendar"></div>
    <script>
      document.addEventListener("DOMContentLoaded", () => {
        // Destructure the Calendar constructor
        const { Calendar } = window.VanillaCalendarPro;
        // Create a calendar instance and initialize it.
        const calendar = new Calendar("#calendar", {
          selectionTimeMode: 24
        });
        calendar.init();
      });
    </script>
  </body>
</html>

```

**Comment by uvarov-frontend** [comment]
Add styles `<body style="display: flex; align-items: start">`
What time are you talking about? The calendar does not set a default time; the choiceTimeMode option only allows you to select and change the time.

**Comment by Allmedialab** [comment]
I mean that the date and time doesn't set in the form but only shows in the GUI. How do you enter the date and time in the form field? id="calendar" There is no enter.

**Comment by uvarov-frontend** [comment]
@Allmedialab I saw your donation, thank you very much, I will try to help you tomorrow, it’s quite late here now.

**Comment by Allmedialab** [comment]
Thanks!

⁣BlueMail voor Android downloaden ​

Op 16 nov. 2024 20:34, om 20:34, Yury Uvarov ***@***.***> schreef:

**Comment by uvarov-frontend** [comment]
@Allmedialab need use `inputMode: true`. See https://vanilla-calendar.pro/docs/learn/type-default#s-input
The fact is that this calendar is not a ready-made solution that you can connect and use without customizing anything. Its purpose is to allow you to implement the date or time picker in a very flexible way.
When you select a date or time you should not expect it to appear somewhere without any additional settings.

For example, to select a date and display it somewhere, it doesn't matter where, you need to use `onClickDate()` to intercept that event, get the necessary data and then do whatever you want with it. same with time, use `onChangeTime()` to intercept this event. All this is available in the documentation: https://vanilla-calendar.pro/docs/reference/actions

I have prepared for you a small example of what you would like to see, as far as I understand. Then you will have to figure it out yourself, use the detailed documentation and the “Learn” section on the site.

Thanks again for your support!

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Vanilla Calendar Pro</title>
    <link href="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/styles/index.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/index.js" defer></script>
  </head>
  <body>
    <input id="calendar" type="text" placeholder="Choose date" readonly />
    <script>
      document.addEventListener("DOMContentLoaded", () => {
        // Destructure the Calendar constructor
        const { Calendar } = window.VanillaCalendarPro;
        // Create a calendar instance and initialize it.
        const calendar = new Calendar("#calendar", {
          inputMode: true,
          positionToInput: "auto",
          selectionTimeMode: 24,
          onChangeToInput(self, event) {
            if (!self.context.inputElement) return;
            const selectedDate = self.context.selectedDates[0];
            self.context.inputElement.value = `${selectedDate ?? ''} ${self.context.selectedTime}`;
            // if you want to hide the calendar after picking a date
            if (event.target.type === "button" && selectedDate) self.hide();
          },
        });
        calendar.init();
      });
    </script>
  </body>
</html>
```
This sandboxed example: https://codesandbox.io/p/sandbox/wispy-dust-g6qmvy

**Comment by Allmedialab** [comment]
Hi,
Thanks for the effort! I am only looking for how to format the date (cant find it in the docs). I want to show it like DDMMYYYY the rest I found on the excelent documentation and is working well. Now it shows 2024-12-01 11:00 and I want it to show like: 01-12-2024. 
Thanks,
David

**Comment by uvarov-frontend** [comment]
I've added a new page to the utilities documentation: https://vanilla-calendar.pro/docs/reference/utilities
You can use them to format dates, but in your case you need to additionally convert the date to another format.

```js
import { getDate } from 'vanilla-calendar-pro/utils';
// or 
// const { getDate } = window.VanillaCalendarProUtils;
getDate('2024-12-01').toLocaleString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).split('/').join('-'); // return: 01-12-2024
```

**Comment by Allmedialab** [comment]
`const { getDate } = window.VanillaCalendarProUtils;
getDate('2024-12-01').toLocaleString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).split('/').join('-');`

Unfortunately doesn't work and gives a error in the console. Where do I have to place this code?

**Comment by uvarov-frontend** [comment]
I forgot to say that to use the utilities you must include the `script` tag if you do not use `import`.

```html
<script src="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/utils/index.js" defer></script>
```

**Comment by Allmedialab** [comment]
`const { getDate } = window.VanillaCalendarProUtils; getDate('2024-12-01').toLocaleString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric' }).split('/').join('-');`
I tried this code but the format of the date is unchanged. Does it matter where I place this code snip?

**Comment by uvarov-frontend** [comment]
Open the previous example please: https://codesandbox.io/p/sandbox/wispy-dust-g6qmvy

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Vanilla Calendar Pro</title>
    <link
      href="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/styles/index.css"
      rel="stylesheet"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/index.js"
      defer
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/utils/index.js"
      defer
    ></script>
  </head>
  <body>
    <input id="calendar" type="text" placeholder="Choose date" readonly />
    <script>
      document.addEventListener("DOMContentLoaded", () => {
        const { Calendar } = window.VanillaCalendarPro;
        const { getDate } = window.VanillaCalendarProUtils;

        const calendar = new Calendar("#calendar", {
          inputMode: true,
          positionToInput: "auto",
          selectionTimeMode: 24,
          onChangeToInput(self, event) {
            if (!self.context.inputElement) return;
            const selectedDate = self.context.selectedDates[0];
            const formatDate = selectedDate
              ? getDate(selectedDate)
                  .toLocaleString("en-GB", {
                    day: "2-digit",
                    month: "2-digit",
                    year: "numeric",
                  })
                  .split("/")
                  .join("-")
              : "";
            self.context.inputElement.value = `${formatDate} ${self.context.selectedTime}`;
            // if you want to hide the calendar after picking a date
            if (event.target.type === "button" && selectedDate) self.hide();
          },
        });
        calendar.init();
      });
    </script>
  </body>
</html>
```

**Comment by Allmedialab** [comment]
Thanks very much!!! Have a nice weekend!!!

**Comment by uvarov-frontend** [comment]
@Allmedialab Glad to help, good luck 😉

**Comment by Allmedialab** [comment]
Hi,

I am sorry to bother you for the last issue I have! When I use the Calendar the validation warning of the form doesn't disappear. When I just type the Time and Date in it does. Do you have any idea on how to solve this.
I have a working example on this test page at the bottom of the page:
https://www.yourweblab.nl/hulp

To replicate the issue just click the submit button and see all the validation warnings appear, only when you put in a Time and Date with your calendar it's the only field where the validation warning doesn't go away.

Thanks,

David
