### ISSUE TITLE
[HELP]How to determine in onChangeToInput that the time is changing?

### ISSUE THREAD

**Issue by anyude** [uvarov-frontend/vanilla-calendar-pro#335]
I created a datetime picker. When I click on a date, the calendar is closed. But when I reopen the calendar, dragging the time slider triggers onChangeToInput instead of just onChangeTime. How can I prevent onChangeToInput or determine in onChangeToInput that only the time is changing?

> Example link: https://codesandbox.io/p/sandbox/youthful-chaplygin-wxjfzc

**Comment by uvarov-frontend** [comment]
Hi. Check out this example: https://github.com/uvarov-frontend/vanilla-calendar-pro/issues/334#issuecomment-2481152634

**Comment by anyude** [comment]
Thanks, it works now. A newbie like me needs lots of examples😂.
