### ISSUE TITLE
[HELP] How to get the selected data after onClick events?

### ISSUE THREAD

**Issue by b2z** [uvarov-frontend/vanilla-calendar-pro#336]
Hello!

I have updated to 3.0.0 and now cannot access the selected data in the `onClick` events. 

1. For example if I click on year `2023` then `self.selectedYear` still will have `2024`. The same is for `selectedMonth` and so on.
My code example
```
onClickYear(self, event) {
            let dates = getDates(self.selectedYear, self.selectedMonth, options);
            dates.then(function(result) {
                calendar.selectedDates = result;
                calendar.update({
                    dates: true,
                });
            })
        }
 ```
       
2. `event.target.dataset.calendarDay` does not work anymore.
```
onClickDate(self, event) {
            const date = event.target.dataset.calendarDay.split('-');
```

Thank you in advance.

**Comment by uvarov-frontend** [comment]
Hi.
1. Use `self.context.selectedYear`, here is an [example](https://vanilla-calendar.pro/docs/learn/handle-click-on-the-year-in-the-year-selection)
2. Instead of `event.target.dataset.calendarDay` use `event.target.parentElement.dataset.vcDate`

**Comment by b2z** [comment]
Thank you! Now  I have the selected data. 

But the calendar for some reason does not want to update, always stays the same. It seems that I am missing something here?
```
calendar.selectedDates = result;
                calendar.update({
                    dates: true,
                });
```
As soon as I remove `calendar.update({dates: true})` it is working, but without my updated data of course :(

**Comment by uvarov-frontend** [comment]
You need to create an example in any js sandbox, I don't have enough information to help you. And you don't need to specify `dates: true` since that's the default.

**Comment by ghiscoding** [comment]
Hello, I think it's not mentioned. or clearly mentioned, in the docs but as a side note, the new version should allow you to call [`calendar.update()`](https://vanilla-calendar.pro/docs/reference/methods#update) (without any argument) to update them all. Perhaps the "All arguments default to true" is what no arguments mean.

**Comment by b2z** [comment]
@ghiscoding the arguments in 2.9 were by default `false`, and in 3.0 they are `true`. That's was a breaking change in my case.
