### ISSUE TITLE
[BUG]  Crush when set popup on some dates

### ISSUE THREAD

**Issue by kudrin** [uvarov-frontend/vanilla-calendar-pro#337]
**⚠️ Important: Bug reports are accepted only for version 3.0.0 or above**
Before submitting a bug report, ensure that you are using at least version **3.0.0** of Vanilla Calendar Pro. Issues reported for earlier versions will not be addressed.

---

**Describe the bug**
Crush when set popup on 30 dec or 31 dec

```js
import { Calendar, type Options } from "vanilla-calendar-pro";

import "vanilla-calendar-pro/styles/index.css";

const options: Options = {
  type: "multiple",
  displayMonthsCount: 12,
  monthsToSwitch: 1,
  selectionDatesMode: "multiple",
  displayDatesOutside: false,
  popups: {
    "2024-12-31": {
      html: '<ul class="vc-popups"><li class="vc-rec-public-holiday">New Year Holiday</li></ul>',
      modifier: "vc-day-public-holiday",
    },
  },
};

const calendar = new Calendar("#calendar", options);
calendar.init();

```

**CodeSandbox example (REQUIRED)**

https://codesandbox.io/p/sandbox/zf9f9r

**Comment by uvarov-frontend** [comment]
Fixed in v3.0.1
