### ISSUE TITLE
[BUG] How do disable clicking on the day of the week (mon-sun)

### ISSUE THREAD

**Issue by rickdoesburg** [uvarov-frontend/vanilla-calendar-pro#340]
**Describe your question**
The days of the week (mon-sun) are buttons which are clickable. They however do not do anything by default. 
I'm talking about:
`<button type="button" class="vc-week__day" role="columnheader" aria-label="Monday" data-vc-week-day="1">Mon</button>`

AFAIK I've read all the pieces of documentation but can't seem to figure out how to turn off these days being `<button>` elements. Is this an option? 

**Additional context**
The HTML of the example on Bilitiki uses `<b>` elements instead of buttons. https://biletiki.vanilla-calendar.pro/en

**Comment by rickdoesburg** [comment]
Thanks for the quick response @uvarov-frontend. I'm not confused by the cursor. I was wondering what them being buttons would mean for accessibility. They are pronounced as buttons and available by keyboard using the tab key. They however do nothing when a user does interact with the buttons. Wouldn't it be nice if they are disabled, or aria-disabled if not in use?

![image](https://github.com/user-attachments/assets/fd36908c-9f08-4659-909f-56acee779e22)

**Comment by uvarov-frontend** [comment]
That's right, we need to fix this, thanks for the report.
