### ISSUE TITLE
[HELP] Use or extend existed methods

### ISSUE THREAD

**Issue by kudrin** [uvarov-frontend/vanilla-calendar-pro#341]
**Describe your question**
Can I use existing methods like handleClickArrow to create custom links outside of the calendar?

Yes, I know that you can override the template. But then you'd have to store a large template in the calendar options.

And how can I extend or override (monkeypatch) these methods if I want to extend their functionality without forking the project?

**Comment by uvarov-frontend** [comment]
I don't understand what you mean, please explain in more detail.

**Comment by uvarov-frontend** [comment]
Open the question again if relevant and provide the necessary data.
