### ISSUE TITLE
[BUG] The calendar is initialized into the input tag when using the set() method

### ISSUE THREAD

**Issue by unwo** [uvarov-frontend/vanilla-calendar-pro#342]
Hello.
I have a problem with z-index modal window in livewire and vanilla-calendar-pro when vanilla-calendar-pro sets inputMode:true.
When the calendar shows, its behind text. Simple example:
[https://codesandbox.io/p/sandbox/reverent-nash-zw3jc6](https://codesandbox.io/p/sandbox/reverent-nash-zw3jc6)
This question like in #259, but i can't find the answer.
The vanilla-calendar-pro is a very good calendar, but i can't use its in this case. I will be very glad if you can improve the calendar behavior. Thank you.

**Comment by uvarov-frontend** [comment]
Hello, the calendar has css classes and needs to be customized as you require. To solve your problem, you need to assign a z-index for the calendar greater than that of the content.

```
.vc {
  z-index: 21;
}
```

https://codesandbox.io/p/sandbox/lively-resonance-dxgrpr

**Comment by unwo** [comment]
Thanks for the quick reply. I looked more closely. It turns out that my problem is different. I have two calendars. One is on a modal window, and the other is not.
I applied method set() to the calendar before its initialization, after that the input changes, it turns into a calendar with the class class=vc. That's why the style .vc { z-index: 21;} didn't work. Look html code:
[https://codesandbox.io/p/sandbox/8n973l](https://codesandbox.io/p/sandbox/8n973l)
Is this some kind of error using the set method?

If I accept method update() after initialization, then everything is fine with the calendar. I solved my problem this way.

**Comment by uvarov-frontend** [comment]
@unwo Oh that's interesting, it's actually a bug, the calendar is initialized inside the input tag when using the `set()` method. Thanks for the report, this needs to be fixed. As a workaround use: `calendarInput.selectedDates = ["2024-12-11"];` instead of: `calendarInput.set({ selectedDates: ["2024-12-11"] });`.
