### ISSUE TITLE
[HELP] Missing dates on mobile.

### ISSUE THREAD

**Issue by khdhhde21** [uvarov-frontend/vanilla-calendar-pro#343]
Hello. I downloaded the .js version of the calendar a year ago. Recently I noticed that it's missing some dates when viewed on mobile, for example on iPhone:
![dates missing](https://github.com/user-attachments/assets/b7d0dcbc-719a-4f5a-8d18-fb7222a5bd4b)

Is this a known bug? 

If it's necessary to upgrade to the latest version, could you please explain how to build the required .js files?

**Comment by uvarov-frontend** [comment]
Honestly, I don’t know how to help you based on one screenshot) This doesn’t give me any information.

**Comment by khdhhde21** [comment]
What information would you like? I could not reproduce this issue on a desktop, so I don't have access to the browser console. Do you have any suggestions?

**Comment by uvarov-frontend** [comment]
You need to update the version to 3.0.0 using [the migration page](https://github.com/uvarov-frontend/vanilla-calendar-pro/wiki/%5BMigration-from-v2.*.*%5D-New-API-for-all-options-and-actions-in-v3.0.0) and then reopen the problem if it persists.

**Comment by khdhhde21** [comment]
Thank you. I was able to fix the issue  by changing padding of the button in .css.
