### ISSUE TITLE
[BUG] It's possible to navigate to a month outside of your allowed date-range on calendar type multiple

### ISSUE THREAD

**Issue by LennertJ** [uvarov-frontend/vanilla-calendar-pro#344]
First of all I want to thank you for the amazing package you've created!

I encountered this bug in version 2.9.6.
To check if I could fix it in the latest release (3.0.1) I've recreated a minimalist demo of my problem on the live-editor of your docs page.

```ts
import { Calendar, type Options } from 'vanilla-calendar-pro';

import 'vanilla-calendar-pro/styles/index.css';

const options: Options = {
  dateMin: '2024-12-01',
  dateMax: '2024-12-31',
  type: 'multiple',
};

const calendar = new Calendar('#calendar', options);
calendar.init();
```
This code should generate a vanilla calendar instance with 2 calendars and the days you can select are limited to the month of December 2024.
Since the time is limited to a single month in a single year I can't use the arrows, year or month buttons to jump to a different month, this is the behavior I expected. However If i use the month-picker in the second calendar I'm able to jump to months outside of the allowed range (December 2024).

I've provided 2 screenshots as an illustration of the issue

Left calendar with the 'expected' behavior:
![image](https://github.com/user-attachments/assets/939206eb-2a72-44f9-a371-8c6dfe00dd3a)

Right calendar with the 'unexpected' behavior:
![image](https://github.com/user-attachments/assets/21067cb2-468c-4d54-a460-5046485b6d25)

It's a tiny bug with a small impact since it only happens for the calendar with type multiple and even then not with all allowed dateranges.  And you still can't select disallowed dates and can easily return to your allowed timerange. But I might as well report it since it's not the behavior I expected.

https://codesandbox.io/p/sandbox/agitated-panka-9gf6tq

**Comment by uvarov-frontend** [comment]
Thanks for the report, I'll fix it.
